### ISSUE TITLE
error in demo.py

### ISSUE THREAD

**Issue by crankyz** [toummHus/HAIR#2]
when launching got this:
ERROR: No matching distribution found for net.model

**Comment by jin-cao-tma** [comment]
Thanks for the reminder, now I have corrected this bug. Feel free to comment if you still find any problem.

**Comment by crankyz** [comment]
Thank you for an answer, but now another error
python demo.py --test_path './test/demo/image.png' --output_path './output/demo/'
Traceback (most recent call last):
  File "demo.py", line 109, in <module>
    net  = HAIRModel().load_from_checkpoint(ckpt_path).to(device)
  File "/home/igorv/anaconda3/envs/hair/lib/python3.8/site-packages/lightning/pytorch/utilities/model_helpers.py", line 121, in wrapper
    raise TypeError(
TypeError: The classmethod `HAIRModel.load_from_checkpoint` cannot be called on an instance. Please call it on the class type and make sure the return value is used.

**Comment by jin-cao-tma** [comment]
> Thank you for an answer, but now another error python demo.py --test_path './test/demo/image.png' --output_path './output/demo/' Traceback (most recent call last): File "demo.py", line 109, in net = HAIRModel().load_from_checkpoint(ckpt_path).to(device) File "/home/igorv/anaconda3/envs/hair/lib/python3.8/site-packages/lightning/pytorch/utilities/model_helpers.py", line 121, in wrapper raise TypeError( TypeError: The classmethod `HAIRModel.load_from_checkpoint` cannot be called on an instance. Please call it on the class type and make sure the return value is used.

Thanks again for the important feedback. It should work now.

**Comment by crankyz** [comment]
line 109 in demo.py must be "net". script launched but I've got only same image in output directory, nothing changed same as use "Tiling" or not. very_simple_demo.py work ok. so very dunno what to do, no errors but no results )
![image3](https://github.com/user-attachments/assets/1e08986a-f1ca-4241-894b-9b3356e7cca0)
![image3](https://github.com/user-attachments/assets/0ba5ed3d-ebc6-45b6-94ab-391cb4af193e)

**Comment by jin-cao-tma** [comment]
> line 109 in demo.py must be "net". script launched but I've got only same image in output directory, nothing changed same as use "Tiling" or not. very_simple_demo.py work ok. so very dunno what to do, no errors but no results ) ![image3](https://private-user-images.githubusercontent.com/38855421/360403899-1e08986a-f1ca-4241-894b-9b3356e7cca0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzUxMTQsIm5iZiI6MTcyNDMzNDgxNCwicGF0aCI6Ii8zODg1NTQyMS8zNjA0MDM4OTktMWUwODk4NmEtZjFjYS00MjQxLTg5NGItOWIzMzU2ZTdjY2EwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDEzNTMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2MTViZGEwYmE5MzY2YzgzNTNiNWQxMjNlYWY5ZmQ2YTFiMGFjNDYwYTE1OGUwMTI3YzVhNjBiZDE5NzgyYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7p0wOgyvU0LZMKuBXZvAqogz_goYbkW8sQfCH-TTONA) ![image3](https://private-user-images.githubusercontent.com/38855421/360404102-0ba5ed3d-ebc6-45b6-94ab-391cb4af193e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzUxMTQsIm5iZiI6MTcyNDMzNDgxNCwicGF0aCI6Ii8zODg1NTQyMS8zNjA0MDQxMDItMGJhNWVkM2QtZWJjNi00NWI2LTk0YWItMzkxY2I0YWYxOTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDEzNTMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhNTdiYTZkZmY0MmQ1NWMxZDgxNTVkNzUxYWY1YzU3MWIxNDZiNjg2NGU1NTA1Y2NkYjMwYjY1MDc3ZWYzYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f_k6-P-V-9MViwU5Vo6m3AcFHXg9mAjEVhfCNpIU5Gg)

Apologize for my carelessness, since I didn't try to run the code myself yesterday. After I corrected the typo in line 109, I tried to run the code, and it worked well, as shown below:
![image](https://github.com/user-attachments/assets/af3216b1-fe44-4d37-8c4b-fdb81923930b)
![image](https://github.com/user-attachments/assets/38f7cf53-8b58-4052-a559-c5898d33f42f)
**Please ensure that you download the pre-trained model (i.e. hair3d.ckpt), and put it in HAIR/ckpt/hair3d.ckpt** to make sure your net is loaded correctly.

**Comment by jin-cao-tma** [comment]
> line 109 in demo.py must be "net". script launched but I've got only same image in output directory, nothing changed same as use "Tiling" or not. very_simple_demo.py work ok. so very dunno what to do, no errors but no results ) ![image3](https://private-user-images.githubusercontent.com/38855421/360403899-1e08986a-f1ca-4241-894b-9b3356e7cca0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzU3ODQsIm5iZiI6MTcyNDMzNTQ4NCwicGF0aCI6Ii8zODg1NTQyMS8zNjA0MDM4OTktMWUwODk4NmEtZjFjYS00MjQxLTg5NGItOWIzMzU2ZTdjY2EwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE0MDQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMmZhYTIzYmU3MWMzNDkwMDVkOTIzNmQwYmE5ODQ2MDI2ZmFmYmIxMjA0NWZjODU3NDViOGU5NGNjNDMzNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mu4-LQzOLl4wh3kOLjjyk1qOLRCM4ylObIGjCIstNRE) ![image3](https://private-user-images.githubusercontent.com/38855421/360404102-0ba5ed3d-ebc6-45b6-94ab-391cb4af193e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzU3ODQsIm5iZiI6MTcyNDMzNTQ4NCwicGF0aCI6Ii8zODg1NTQyMS8zNjA0MDQxMDItMGJhNWVkM2QtZWJjNi00NWI2LTk0YWItMzkxY2I0YWYxOTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE0MDQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyYTk0NmU3MmQxY2EyNzUxOWI2NGYxMGRmNjcwOGQ4MTFiYjI0NzYzMGU2ZTczNmFkN2M2YmRkNjUwMmY3MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M4bFFWR2uPghwANp3o4__NmMiS8XqLnQnSRgN6vo9CU)

Still, it's very, very strange to get the same image as the output, since the net will never be a identity mapping. Please check your setting again: did you enter the correct path?  
It's suggested to directly download the new version of our code and try again. Contact me if you still find any bug

**Comment by crankyz** [comment]
thank you for a fast answer. as I tried derain on your picture worked well, but denoising on a picture with "wolf" actually not (
![5](https://github.com/user-attachments/assets/1b6f9995-9ca6-4ec5-95b8-3fc3db229da4) and on a picture like this same (
but on this worked fine with deraining
![6](https://github.com/user-attachments/assets/dcc11559-0c50-4183-bd0d-f3b89c15a6f1)

**Comment by jin-cao-tma** [comment]
> thank you for a fast answer. as I tried derain on your picture worked well, but denoising on a picture with "wolf" actually not ( ![5](https://private-user-images.githubusercontent.com/38855421/360565376-1b6f9995-9ca6-4ec5-95b8-3fc3db229da4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNzIwMTQsIm5iZiI6MTcyNDM3MTcxNCwicGF0aCI6Ii8zODg1NTQyMS8zNjA1NjUzNzYtMWI2Zjk5OTUtOWNhNi00ZWM1LTk1YjgtM2ZjM2RiMjI5ZGE0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDAwMDgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMDViNTc0YmE4MGYyMDNkZjIwNGMxMjVhYmZmMTY3ODQzY2RhZmEyMTdiY2Y4OWRiNzFkY2ZiMmU5NWY4YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._RMNUGW3uP6PoqP7VLVhfGkmfa0jGeXfc2rE_v3aTwY) and on a picture like this same ( but on this worked fine with deraining ![6](https://private-user-images.githubusercontent.com/38855421/360567017-dcc11559-0c50-4183-bd0d-f3b89c15a6f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNzIwMTQsIm5iZiI6MTcyNDM3MTcxNCwicGF0aCI6Ii8zODg1NTQyMS8zNjA1NjcwMTctZGNjMTE1NTktMGM1MC00MTgzLWJkMGQtZjNiODljMTVhNmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDAwMDgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmOGZlYjEyYTZlYjA4YWU5MmFmZjM5ZjQyMTQzNjZhYTczODk5Y2FlMDBlMjliMTU2YjMwYzMxYjY0NGZkYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bVR31f01D0iQ7VpLl2ZcDbg3HtMeD5jwbc3BK-gbvSY)

For the derain, the results are normal since the model are only trained with the second type of raindrops. 
For the denoise task, I know where is wrong: it seems like you directly use the image I present in my paper as the degraded image, then there is no wonder it fail to work. The image I presented are specially processed to look clearer, so it is no longer a simple "Gaussian noisy image". Please use this noisy image and try again.
![noisy_25_17](https://github.com/user-attachments/assets/5e8b3d0d-9644-4b15-a2c4-be1c36d908c4)

**Comment by jin-cao-tma** [comment]
For gaussian denoising, please ensure your input is only with a gaussian noise with a std of {15,25,50} in the value range of [0,255]
